package patterns

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func sampleInput() Input {
	return Input{
		ProjectName: "MyProject",
		Blueprint:   "A microservices architecture with an API gateway, auth service, and data layer backed by PostgreSQL.",
		Patterns: []string{
			"Dependency injection via constructor functions",
			"Interface-based abstractions for testability",
			"Context propagation for cancellation and tracing",
		},
		Zones: []Zone{
			{
				Name:   "authentication",
				Intent: "Handles user login, registration, and credential verification",
				Files:  []string{"auth/login.go", "auth/register.go", "auth/credentials.go"},
			},
			{
				Name:   "billing",
				Intent: "Manages subscriptions, invoices, and payment processing",
				Files:  []string{"billing/subscription.go", "billing/invoice.go"},
			},
		},
		Modules: []ModuleSummary{
			{
				Name:   "auth",
				Intent: "Provides authentication and session management",
				Type:   "go",
			},
			{
				Name:   "web-ui",
				Intent: "React-based frontend for the dashboard",
				Type:   "node",
			},
			{
				Name:   "ml-pipeline",
				Intent: "Data processing and model training pipeline",
				Type:   "python",
			},
		},
	}
}

func TestGenerateCLAUDE_ContainsSections(t *testing.T) {
	input := sampleInput()
	output := GenerateCLAUDE(input)

	// Project name as heading.
	if !strings.Contains(output, "# MyProject") {
		t.Error("output should contain project name heading")
	}

	// Architecture section with blueprint.
	if !strings.Contains(output, "## Architecture") {
		t.Error("output should contain Architecture section")
	}
	if !strings.Contains(output, "microservices architecture") {
		t.Error("output should contain the blueprint text")
	}

	// Modules section.
	if !strings.Contains(output, "## Modules") {
		t.Error("output should contain Modules section")
	}
	if !strings.Contains(output, "### auth (go)") {
		t.Error("output should contain auth module heading with type")
	}
	if !strings.Contains(output, "### web-ui (node)") {
		t.Error("output should contain web-ui module heading with type")
	}
	if !strings.Contains(output, "### ml-pipeline (python)") {
		t.Error("output should contain ml-pipeline module heading with type")
	}
	if !strings.Contains(output, "Provides authentication and session management") {
		t.Error("output should contain module intent text")
	}

	// Business Domains section.
	if !strings.Contains(output, "## Business Domains") {
		t.Error("output should contain Business Domains section")
	}
	if !strings.Contains(output, "### authentication") {
		t.Error("output should contain authentication zone heading")
	}
	if !strings.Contains(output, "Handles user login") {
		t.Error("output should contain zone intent")
	}
	if !strings.Contains(output, "- auth/login.go") {
		t.Error("output should list zone files")
	}
	if !strings.Contains(output, "### billing") {
		t.Error("output should contain billing zone heading")
	}

	// Coding Patterns section.
	if !strings.Contains(output, "## Coding Patterns") {
		t.Error("output should contain Coding Patterns section")
	}
	if !strings.Contains(output, "- Dependency injection via constructor functions") {
		t.Error("output should list patterns as bullet points")
	}
	if !strings.Contains(output, "- Interface-based abstractions for testability") {
		t.Error("output should contain second pattern")
	}

	// Working with the Carto Index section.
	if !strings.Contains(output, "## Working with the Carto Index") {
		t.Error("output should contain Working with the Carto Index section")
	}
	if !strings.Contains(output, "memory_search") {
		t.Error("output should contain MCP memory_search instruction")
	}
	if !strings.Contains(output, "memory_add") {
		t.Error("output should contain MCP memory_add instruction")
	}
	if !strings.Contains(output, "$MEMORIES_URL/search") {
		t.Error("output should contain curl search fallback")
	}
	if !strings.Contains(output, "$MEMORIES_URL/memory/add") {
		t.Error("output should contain curl write-back fallback")
	}
	if !strings.Contains(output, "Summary:") {
		t.Error("output should contain atom format with Summary field")
	}
	if !strings.Contains(output, "### Follow Discovered Patterns") {
		t.Error("output should contain Follow Discovered Patterns subsection")
	}

	// Footer.
	if !strings.Contains(output, "*Generated by Carto v1.0.0*") {
		t.Error("output should contain the generated-by footer")
	}
}

func TestGenerateCLAUDE_EmptyInput(t *testing.T) {
	input := Input{ProjectName: "EmptyProject"}
	output := GenerateCLAUDE(input)

	if !strings.Contains(output, "# EmptyProject") {
		t.Error("output should contain project name even with empty input")
	}
	if !strings.Contains(output, "## Architecture") {
		t.Error("output should contain Architecture section even when empty")
	}
	// Should not contain Modules section when there are no modules.
	if strings.Contains(output, "## Modules") {
		t.Error("output should not contain Modules section when there are no modules")
	}
	// Should not contain Business Domains section when there are no zones.
	if strings.Contains(output, "## Business Domains") {
		t.Error("output should not contain Business Domains section when there are no zones")
	}
	// Should not contain Coding Patterns section when there are no patterns.
	if strings.Contains(output, "## Coding Patterns") {
		t.Error("output should not contain Coding Patterns section when there are no patterns")
	}
	if !strings.Contains(output, "*Generated by Carto v1.0.0*") {
		t.Error("output should contain footer even with empty input")
	}
}

func TestGenerateCursorRules_ContainsSections(t *testing.T) {
	input := sampleInput()
	output := GenerateCursorRules(input)

	// Project name.
	if !strings.Contains(output, "Project: MyProject") {
		t.Error("output should contain project name")
	}

	// Architecture.
	if !strings.Contains(output, "Architecture:") {
		t.Error("output should contain Architecture label")
	}
	if !strings.Contains(output, "microservices architecture") {
		t.Error("output should contain blueprint text")
	}

	// Modules.
	if !strings.Contains(output, "Modules:") {
		t.Error("output should contain Modules label")
	}
	if !strings.Contains(output, "- auth (go): Provides authentication and session management") {
		t.Error("output should list modules in compact format")
	}
	if !strings.Contains(output, "- web-ui (node): React-based frontend") {
		t.Error("output should list web-ui module")
	}
	if !strings.Contains(output, "- ml-pipeline (python): Data processing") {
		t.Error("output should list ml-pipeline module")
	}

	// Patterns.
	if !strings.Contains(output, "Patterns:") {
		t.Error("output should contain Patterns label")
	}
	if !strings.Contains(output, "- Dependency injection via constructor functions") {
		t.Error("output should list patterns")
	}

	// Business Domains.
	if !strings.Contains(output, "Business Domains:") {
		t.Error("output should contain Business Domains label")
	}
	if !strings.Contains(output, "- authentication: Handles user login") {
		t.Error("output should list zones in compact format")
	}
	if !strings.Contains(output, "- billing: Manages subscriptions") {
		t.Error("output should list billing zone")
	}

	// Working with the Carto Index instructions.
	if !strings.Contains(output, "Working with the Carto Index:") {
		t.Error("output should contain Working with the Carto Index label")
	}
	if !strings.Contains(output, "Query before editing") {
		t.Error("output should contain query-before-edit instruction")
	}
	if !strings.Contains(output, "Write back after changes") {
		t.Error("output should contain write-back instruction")
	}
	if !strings.Contains(output, "$MEMORIES_URL/search") {
		t.Error("output should contain search curl command")
	}
	if !strings.Contains(output, "$MEMORIES_URL/memory/add") {
		t.Error("output should contain write-back curl command")
	}
}

func TestGenerateCursorRules_EmptyInput(t *testing.T) {
	input := Input{ProjectName: "EmptyProject"}
	output := GenerateCursorRules(input)

	if !strings.Contains(output, "Project: EmptyProject") {
		t.Error("output should contain project name even with empty input")
	}
	if !strings.Contains(output, "Architecture:") {
		t.Error("output should contain Architecture label even when empty")
	}
	// Should not contain Modules label when there are no modules.
	if strings.Contains(output, "Modules:") {
		t.Error("output should not contain Modules label when there are no modules")
	}
	// Should not contain Patterns label when there are no patterns.
	if strings.Contains(output, "Patterns:") {
		t.Error("output should not contain Patterns label when there are no patterns")
	}
	// Should not contain Business Domains label when there are no zones.
	if strings.Contains(output, "Business Domains:") {
		t.Error("output should not contain Business Domains label when there are no zones")
	}
}

func TestWriteFiles_All(t *testing.T) {
	dir := t.TempDir()
	input := sampleInput()

	err := WriteFiles(dir, input, "all")
	if err != nil {
		t.Fatalf("WriteFiles(all) returned error: %v", err)
	}

	// Verify CLAUDE.md was created.
	claudePath := filepath.Join(dir, "CLAUDE.md")
	claudeData, err := os.ReadFile(claudePath)
	if err != nil {
		t.Fatalf("CLAUDE.md not created: %v", err)
	}
	if !strings.Contains(string(claudeData), "# MyProject") {
		t.Error("CLAUDE.md should contain project name")
	}

	// Verify .cursorrules was created.
	cursorPath := filepath.Join(dir, ".cursorrules")
	cursorData, err := os.ReadFile(cursorPath)
	if err != nil {
		t.Fatalf(".cursorrules not created: %v", err)
	}
	if !strings.Contains(string(cursorData), "Project: MyProject") {
		t.Error(".cursorrules should contain project name")
	}
}

func TestWriteFiles_ClaudeOnly(t *testing.T) {
	dir := t.TempDir()
	input := sampleInput()

	err := WriteFiles(dir, input, "claude")
	if err != nil {
		t.Fatalf("WriteFiles(claude) returned error: %v", err)
	}

	// Verify CLAUDE.md was created.
	claudePath := filepath.Join(dir, "CLAUDE.md")
	if _, err := os.Stat(claudePath); err != nil {
		t.Fatalf("CLAUDE.md should exist: %v", err)
	}

	// Verify .cursorrules was NOT created.
	cursorPath := filepath.Join(dir, ".cursorrules")
	if _, err := os.Stat(cursorPath); !os.IsNotExist(err) {
		t.Error(".cursorrules should not exist when format is 'claude'")
	}
}

func TestWriteFiles_CursorOnly(t *testing.T) {
	dir := t.TempDir()
	input := sampleInput()

	err := WriteFiles(dir, input, "cursor")
	if err != nil {
		t.Fatalf("WriteFiles(cursor) returned error: %v", err)
	}

	// Verify .cursorrules was created.
	cursorPath := filepath.Join(dir, ".cursorrules")
	if _, err := os.Stat(cursorPath); err != nil {
		t.Fatalf(".cursorrules should exist: %v", err)
	}

	// Verify CLAUDE.md was NOT created.
	claudePath := filepath.Join(dir, "CLAUDE.md")
	if _, err := os.Stat(claudePath); !os.IsNotExist(err) {
		t.Error("CLAUDE.md should not exist when format is 'cursor'")
	}
}

func TestWriteFiles_InvalidFormat(t *testing.T) {
	dir := t.TempDir()
	input := sampleInput()

	err := WriteFiles(dir, input, "invalid")
	if err == nil {
		t.Fatal("WriteFiles should return error for invalid format")
	}
	if !strings.Contains(err.Error(), "unknown format") {
		t.Errorf("error should mention unknown format, got: %v", err)
	}
}

func TestWriteFiles_CreatesDirectory(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "output")
	input := sampleInput()

	err := WriteFiles(dir, input, "all")
	if err != nil {
		t.Fatalf("WriteFiles should create nested directory: %v", err)
	}

	// Both files should exist.
	if _, err := os.Stat(filepath.Join(dir, "CLAUDE.md")); err != nil {
		t.Error("CLAUDE.md should exist in nested directory")
	}
	if _, err := os.Stat(filepath.Join(dir, ".cursorrules")); err != nil {
		t.Error(".cursorrules should exist in nested directory")
	}
}

func TestGenerateCLAUDE_ZoneFilesListed(t *testing.T) {
	input := Input{
		ProjectName: "Test",
		Zones: []Zone{
			{
				Name:   "payments",
				Intent: "Handles payment processing",
				Files:  []string{"pay/charge.go", "pay/refund.go", "pay/webhook.go"},
			},
		},
	}
	output := GenerateCLAUDE(input)

	// All three files should appear.
	for _, f := range input.Zones[0].Files {
		if !strings.Contains(output, "- "+f) {
			t.Errorf("output should list file %q", f)
		}
	}
}

func TestWriteFiles_PreservesExistingContent(t *testing.T) {
	dir := t.TempDir()
	input := sampleInput()

	// Write existing CLAUDE.md with user content.
	existingClaude := "# My Project\n\nThis is my project's existing CLAUDE.md with custom instructions.\n\n## My Custom Section\n\nDo not delete this.\n"
	if err := os.WriteFile(filepath.Join(dir, "CLAUDE.md"), []byte(existingClaude), 0o644); err != nil {
		t.Fatal(err)
	}

	// Write existing .cursorrules with user content.
	existingCursor := "Custom cursor rules here.\nDo not overwrite.\n"
	if err := os.WriteFile(filepath.Join(dir, ".cursorrules"), []byte(existingCursor), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := WriteFiles(dir, input, "all"); err != nil {
		t.Fatalf("WriteFiles failed: %v", err)
	}

	// CLAUDE.md should contain both the original content and the Carto section.
	claudeData, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	claudeStr := string(claudeData)
	if !strings.Contains(claudeStr, "This is my project's existing CLAUDE.md") {
		t.Error("CLAUDE.md should preserve existing user content")
	}
	if !strings.Contains(claudeStr, "My Custom Section") {
		t.Error("CLAUDE.md should preserve custom sections")
	}
	if !strings.Contains(claudeStr, "microservices architecture") {
		t.Error("CLAUDE.md should contain the Carto-generated blueprint")
	}
	if !strings.Contains(claudeStr, cartoBeginMarker) {
		t.Error("CLAUDE.md should contain the Carto begin marker")
	}
	if !strings.Contains(claudeStr, cartoEndMarker) {
		t.Error("CLAUDE.md should contain the Carto end marker")
	}

	// .cursorrules should contain both original and Carto content.
	cursorData, err := os.ReadFile(filepath.Join(dir, ".cursorrules"))
	if err != nil {
		t.Fatal(err)
	}
	cursorStr := string(cursorData)
	if !strings.Contains(cursorStr, "Custom cursor rules here") {
		t.Error(".cursorrules should preserve existing content")
	}
	if !strings.Contains(cursorStr, "microservices architecture") {
		t.Error(".cursorrules should contain Carto-generated content")
	}
}

func TestWriteFiles_UpdatesExistingCartoSection(t *testing.T) {
	dir := t.TempDir()

	// First write with initial input.
	input1 := Input{
		ProjectName: "OldProject",
		Blueprint:   "Old architecture.",
	}
	existingContent := "# My Project\n\nUser instructions.\n"
	if err := os.WriteFile(filepath.Join(dir, "CLAUDE.md"), []byte(existingContent), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := WriteFiles(dir, input1, "claude"); err != nil {
		t.Fatal(err)
	}

	// Second write with updated input — should replace the Carto section.
	input2 := Input{
		ProjectName: "NewProject",
		Blueprint:   "New architecture.",
	}
	if err := WriteFiles(dir, input2, "claude"); err != nil {
		t.Fatal(err)
	}

	claudeData, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if err != nil {
		t.Fatal(err)
	}
	claudeStr := string(claudeData)

	// User content preserved.
	if !strings.Contains(claudeStr, "User instructions.") {
		t.Error("should preserve user content after update")
	}
	// Old Carto content replaced.
	if strings.Contains(claudeStr, "Old architecture") {
		t.Error("old Carto content should be replaced")
	}
	if strings.Contains(claudeStr, "OldProject") {
		t.Error("old project name should be replaced")
	}
	// New Carto content present.
	if !strings.Contains(claudeStr, "New architecture") {
		t.Error("new Carto content should be present")
	}
	// Only one begin/end marker pair.
	if strings.Count(claudeStr, cartoBeginMarker) != 1 {
		t.Errorf("should have exactly 1 begin marker, got %d", strings.Count(claudeStr, cartoBeginMarker))
	}
}

func TestWriteFiles_ContentRoundTrip(t *testing.T) {
	dir := t.TempDir()
	input := sampleInput()

	if err := WriteFiles(dir, input, "all"); err != nil {
		t.Fatalf("WriteFiles failed: %v", err)
	}

	// Read CLAUDE.md and verify it contains the generated content within markers.
	claudeData, err := os.ReadFile(filepath.Join(dir, "CLAUDE.md"))
	if err != nil {
		t.Fatalf("failed to read CLAUDE.md: %v", err)
	}
	claudeStr := string(claudeData)
	generated := GenerateCLAUDE(input)
	if !strings.Contains(claudeStr, generated) {
		t.Error("CLAUDE.md should contain the GenerateCLAUDE output")
	}
	if !strings.Contains(claudeStr, cartoBeginMarker) {
		t.Error("CLAUDE.md should contain begin marker")
	}
	if !strings.Contains(claudeStr, cartoEndMarker) {
		t.Error("CLAUDE.md should contain end marker")
	}

	// Read .cursorrules and verify it contains the generated content within markers.
	cursorData, err := os.ReadFile(filepath.Join(dir, ".cursorrules"))
	if err != nil {
		t.Fatalf("failed to read .cursorrules: %v", err)
	}
	cursorStr := string(cursorData)
	generatedCursor := GenerateCursorRules(input)
	if !strings.Contains(cursorStr, generatedCursor) {
		t.Error(".cursorrules should contain the GenerateCursorRules output")
	}
}
